// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('tiwoApp').controller('MainCtrl', [
  '$scope', 'taskService', 'timeService', function($scope, taskService, timeService) {
    $scope.model = {};
    $scope.getTasks = function() {
      return taskService.get();
    };
    $scope.model.tasks = $scope.getTasks();
    $scope.model.curTask = {};
    $scope.model.nextTask = {};
    $scope.model.taskNames = taskService.getTaskNames();
    $scope.model.tempTasks = [
      {
        show: true
      }, {
        show: true
      }, {
        show: false,
        taskName: 'test'
      }
    ];
    $scope.clearAll = function() {
      taskService.clearAll();
      $scope.model.tasks = $scope.getTasks();
      return $scope.model.taskNames = taskService.getTaskNames();
    };
    $scope.addItem = function(item) {
      return item.startTime = timeService.parseDate(item.startTime).then(function(data) {
        item.startTime = data;
        return timeService.parseDate(item.endTime);
      }).then(function(data) {
        item.endTime = data;
        return timeService.dateDiff(item.startTime, item.endTime, "h");
      }).then(function(data) {
        item.duration = data;
        taskService.add(item);
        $scope.model.tasks = $scope.getTasks();
        $scope.model.curTask = {};
        return $scope.model.taskNames = taskService.getTaskNames();
      });
    };
    return $scope.$watch('model.tasks', function(newValue, oldValue) {
      var item, _i, _len;
      if (!angular.equals(newValue, oldValue) && newValue) {
        for (_i = 0, _len = newValue.length; _i < _len; _i++) {
          item = newValue[_i];
          taskService.update(item);
        }
        return $scope.model.taskNames = taskService.getTaskNames();
      }
    }, true);
  }
]);
