// Generated by CoffeeScript 1.6.3
'use strict';
describe('Service: timeService', function() {
  var rootScope, timeService;
  beforeEach(module('tiwoApp'));
  timeService = {};
  rootScope = null;
  beforeEach(inject(function(_timeService_, $rootScope) {
    timeService = _timeService_;
    return rootScope = $rootScope;
  }));
  it('should do something', function() {
    return expect(!!timeService).toBe(true);
  });
  it('should expect 3a to be parsed as a date at 3am', function() {
    var result;
    result = timeService.parseDate('3a').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    return expect(result.getHours()).toBe(3);
  });
  it('should expect 3p to be parsed as a date at 3pm', function() {
    var result;
    result = timeService.parseDate('3p').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    return expect(result.getHours()).toBe(15);
  });
  it('should expect 3pm to be parsed as a date at 3pm', function() {
    var result;
    result = timeService.parseDate('3p').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    return expect(result.getHours()).toBe(15);
  });
  it('should expect 3a to be parsed as a date at 3am', function() {
    var result;
    result = timeService.parseDate('3a').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    return expect(result.getHours()).toBe(3);
  });
  it('should expect 01/01/2012 to be parsed as a date at of Jan 1st, 2012', function() {
    var result;
    result = timeService.parseDate('01/01/2012').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    expect(result.getMonth()).toBe(0);
    expect(result.getFullYear()).toBe(2012);
    return expect(result.getDate()).toBe(1);
  });
  it('should expect 01/01/2012 3am to be parsed as a date at of Jan 1st, 2012 at 3am', function() {
    var result;
    result = timeService.parseDate('01/01/2012 3am').then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    expect(result.getMonth()).toBe(0);
    expect(result.getFullYear()).toBe(2012);
    expect(result.getDate()).toBe(1);
    return expect(result.getHours()).toBe(3);
  });
  return it('should expect 9am-10am to have a time difference of 1 hour', function() {
    var endDate, result, startDate;
    startDate = new Date();
    startDate.setHours(9);
    startDate.setMinutes(0);
    startDate.setSeconds(0);
    endDate = new Date();
    endDate.setHours(10);
    endDate.setMinutes(0);
    endDate.setSeconds(0);
    result = timeService.dateDiff(startDate, endDate).then(function(data) {
      return result = data;
    });
    rootScope.$apply();
    return expect(result).toBe(1);
  });
});
